version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - portfolio_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "3000"
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/portfolio
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - portfolio_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=portfolio
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - portfolio_network

volumes:
  mysql_data:

networks:
  portfolio_network:
    driver: bridge 