version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - RESEND_API_KEY=${RESEND_API_KEY}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
    networks:
      - webportofolio-network

networks:
  webportofolio-network:
    driver: bridge
    name: webportofolio-network
